### ISSUE TITLE
Formulate simple memory management idea

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-ideas#1]
### Requirements

- Don't introduce an allocator or GC that is bigger than simple Tacit programs
- Rely on system memory management principles where possible
- Do something with well-understood behaviour (i.e. not unproven region-based management)

### Tasks

- [x] Sketch out some page-based allocation options
- [x] Compare small allocations to CPU cache line
- [x] Find that system call (e.g. look in jemalloc) and see if individual pages can be returned after a multipage acquisition
- [x] Check my system's huge page support (including mmap rights)
- [x] Look for a CLZ equivalent (count leading zeroes or get position of first non-zero bit) for x64
- [x] Research segmented stack best practices (probably required for green threads, relevant to stack+heap memory management)
- [x] Go through allocations for each power-of-two-plus-one, calculating wasted space and marking the allocation scheme
  - [x] Make sure adding the page index is only a minor fraction of wasted space (e.g. ⅛ or 1/16)
  - [x] Instead of doing multi-level indexes, increase the index size by power of twos
- [x] Pick a final solution
- [x] Find out how to change memory protection (upgrade from inaccessible)
- [x] Check if `PROT_NONE` counts as overcommitting
- [x] Consider using unallocated page pointers for lazily-allocated sparse arrays
- [x] Check how jemalloc [handles](http://jemalloc.net/jemalloc.3.html#implementation_notes) threads
- [x] Document results as an idea here

**Comment by dcecile** [comment]
- Jemalloc [uses mmap with file descriptor -1](https://github.com/jemalloc/jemalloc/blob/master/src/pages.c#L79) (or VirtualAlloc) for a specific address
- It seems like VirtualAlloc has a [minimum size of 64 KB](https://blogs.msdn.microsoft.com/oldnewthing/20031008-00/?p=42223) ([GetSystemInfo.dwAllocationGranularity](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/ns-sysinfoapi-_system_info))
- muslc's [mmap](https://github.com/seL4/musllibc/blob/sel4/src/mman/mmap.c) (AKA [Posix mmap](http://pubs.opengroup.org/onlinepubs/7908799/xsh/mmap.html)) directly translates to Linux x64's syscall 9, AKA [sys_mmap](http://man7.org/linux/man-pages/man2/mmap.2.html)
- Posix doesn't mention skipping address or file descriptor, but Linux says skipping the address results in system-determined allocation and that -1 file descriptor is used for anonymous mappings (not backed by files)
- Linux supports multiple alternate page sizes via ["huge pages"](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt)
- munmap allows returning individual pages back to the OS even if they were all allocated together, seems a bit more [complicated on Windows](https://blogs.msdn.microsoft.com/oldnewthing/20170113-00/?p=95185) but still doable
- CPU cores have a limit to the number of TLB entries they can map at a time (for all processes)
- Huge pages are physically contiguous
- In Windows, VirtualAlloc has the same address skipping mechanism and [large page support](https://msdn.microsoft.com/060115af-38d1-499c-b30c-47cd0cf42d20)

**Comment by dcecile** [comment]
- After using [madvise](http://man7.org/linux/man-pages/man2/madvise.2.html), I was able to get `watch -n 1 /proc/meminfo` to show usage of anonymous huge pages
- This is done using [transparent huge page support](https://www.kernel.org/doc/Documentation/vm/transhuge.txt)
- The max for one madvise was 16 MiB, anything after that didn't get put into huge page(s)
- The min for one madvise was 4 MiB
- Use madvise multiple times didn't change anything, so maybe it's a per-process limit?

**Comment by dcecile** [comment]
- AMD x64 Volume 1 (Application Programming), _Section 3.3.8 Bit Manipulation_ has all of the instructions
- There's LZCNT to count the leading zeroes and BSR (hinted at in [Stack Overflow](https://stackoverflow.com/a/11376759/207321)) to find the index of the most significant bit
- In AMD x64 Volume 3, it's clear that BSR supports 16-bit, 32-bit, and 64-bit operands

**Comment by dcecile** [comment]
- [mprotect](http://man7.org/linux/man-pages/man2/mprotect.2.html), syscall 9, is definitely the one for upgrading memory pages to be readable & writable
- I don't foresee any problems using this

**Comment by dcecile** [comment]
- `PROT_NONE` is specifically for avoiding overcommitting

**Comment by dcecile** [comment]
- Jemalloc implements its `tsd_get` using [`pthread_create_key`](https://github.com/jemalloc/jemalloc/blob/master/include/jemalloc/internal/tsd_tls.h#L13) or [`TlsGetValue`](https://github.com/jemalloc/jemalloc/blob/master/include/jemalloc/internal/tsd_win.h#L49)
- This is used in every operation via [`tsd_fetch`](https://github.com/jemalloc/jemalloc/blob/master/src/jemalloc.c#L1999)
- Alternatively, Windows PE provides a [`.tls` section](https://docs.microsoft.com/en-ca/windows/desktop/Debug/pe-format#the-tls-section) and ELF has a [`.tbss` section](http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/specialsections.html)
