### ISSUE TITLE
Formulate simple I/O idea

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-ideas#2]
### Requirements
- No behind-the-scenes buffering
- Compatibility with co-operative multithreading and async I/O (completion handlers)
- Support network and streaming I/O use cases
- Support disk cache use cases
- Support write-ahead-log use case
- Support read-whole-file and write-whole-file use cases

### Tasks
- [x] Find out if mmap files can give signals on page fault
- [x] See if it's possible to allocate pages that are unreadable, unwritable, and unexecutable in order to generate custom segfaults (triggering async reads and dirty-page flags)
- [x] Consider [Linux Copy-On-Write example](https://drawings.jvns.ca/copyonwrite/)
- [x] Double check Linux and Windows capability for async file reading/writing
- [x] Check what `MADV_FREE` "swap required" means
- [x] Find a Windows equivalent for `MADV_FREE`
- [x] Check the benefits of random access reading & writing
- [x] Find out how to make sure `MADV_FREE` doesn't get a new page at that location
- [x] Pick a final solution
- [x] Name the primitive
- [x] Document results as an idea here

**Comment by dcecile** [comment]
- Page faults are really SIGSEGV that get handled by the kernel before the user can see them, there's no way to get immediate feedback
- There also seems no way to get immediate feedback of other process faulting or stalling
- Linux implements an [LRU-like eviction policy](https://www.kernel.org/doc/gorman/html/understand/understand013.html)

**Comment by dcecile** [comment]
- Found a nice, [modern Linux async file IO tutorial](http://kkourt.io/blog/2017/10-14-linux-aio.html) with details that it's [compatible](https://linux.die.net/man/2/eventfd) with poll, epoll, select, etc.
- Sometimes those syscalls will block
- There's also an [old C++ demo of completion port Windows async IO](https://code.msdn.microsoft.com/windowsdesktop/CppAsynchronousIO-a3f7c07d#content)
- There's a Hacker News thread [debating pros/cons of Windows async IO](https://news.ycombinator.com/item?id=11866562)
- Both sounds kind of shaky, and don't cover all I/O use cases (open file, read directory, delete file, etc.)

**Comment by dcecile** [comment]
- Starting with Linux 4.12, `MADV_FREE` [can work on swapless systems](https://github.com/torvalds/linux/commit/93e06c7a645343d222c9a838834a51042eebbbf7#diff-4857956475e4ff45719ec51a2eac4547)
- The previous check was literally if you had swap pages, available via [`sysinfo`](http://man7.org/linux/man-pages/man2/sysinfo.2.html)

**Comment by dcecile** [comment]
- The [survey of Windows memory freeing](https://blogs.msdn.microsoft.com/oldnewthing/20170113-00/?p=95185) gives a bit of a guide
- [OfferVirtualMemory](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-offervirtualmemory) makes it inaccessible
- [DiscardVirtualMemory](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-discardvirtualmemory) makes it undefined
- [VirtualUnlock](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-virtualunlock) sounds like a no-op, leaving the page swappable
- [VirtualAlloc + MEM_RESET](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-virtualalloc) leaves zeroes behind if the page was evicted

**Comment by dcecile** [comment]
Memory mapped file I/O...

#### Pros

- If read-only, can be shared between multiple threads, without any locking needed for reading or eviction
- Simple model for developers, read from and write to memory, flush when needed
  - Versus manually scheduling block I/O calls
- Block I/O is generally built on top of files memory mapped into kernel space
- Uses the OS eviction algorithm which would be hard to beat
- Puts less load on the system due to fewer buffer copies
- Automatically tracks which parts of the file to write during a flush
- Memory already backed by files can be safely evicted without writing again to a swap file
- Automatic reading ahead based on access patterns

#### Cons

- OS-handled page faults interfere with cooperative multithreading
- Needs disk data to already be formatted "well enough"
- Not useful if you discard (or transform) the data immediately after reading it
- Because it changes the TLB and page faulting requires context switching, it's inefficient for reading very small files
- Once working memory is saturated, every page fault fault also triggers an expensive eviction
- Page tables for large memory-mapped files take up considerable space
- Developer has no control over I/O priorities or queuing
- More threads are needed to keep the CPU busy while other threads are page faulting
- Disk blocks are usually only 512 bytes, but full OS pages need to be read/written
- Writes too far behind or reads too far ahead will thrash the CPU caches

#### Neutral

- Forms the basis of IPC
- Linux "direct" async I/O bypasses the OS caches

#### Use cases

- Databases (file or block device)
- Disk caches
- Read-only, shared, dynamic libraries

**Comment by dcecile** [comment]
- MADV_FREE results in zero-fill pages later, just like MEM_RESET on Windows -- it won't give the virtual address space away to other allocations

**Comment by dcecile** [comment]
- For page fault stats, [`get_rusage`](https://stackoverflow.com/a/23317928/207321) works for Linux
- Performance counters [might be able to do the same for Windows](https://stackoverflow.com/a/6416885/207321), and [event tracing](https://docs.microsoft.com/en-us/windows/desktop/etw/pagefault-hardfault) can get the data at per-fault granularity
- Maybe comparing [commit charge to working](https://docs.microsoft.com/en-ca/windows/desktop/api/psapi/ns-psapi-_process_memory_counters_ex) set can give a level of swap usage on Windows
- [GlobalMemoryStatusEx](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex) can get total free system memory in Windows, with [/proc/meminfo](http://man7.org/linux/man-pages/man5/proc.5.html) as the Linux equivalent
- Raymond Chen suggests avoiding any [use up to %X free physical memory](https://blogs.msdn.microsoft.com/oldnewthing/20120118-00/?p=8513/) caching schemes
- Chris Down says [Linux doesn't have great memory pressure indicators](https://chrisdown.name/2018/01/02/in-defence-of-swap.html#ok-so-i-want-system-swap-but-how-can-i-tune-it-for-individual-applications)
- Johannes Weiner says [the OOM killer doesn't kick in until well after latency degrades](https://lkml.org/lkml/2018/8/28/816)
- New Linus "process stall indicators" are [included in 4.20](https://github.com/torvalds/linux/commit/2ce7135adc9ad081aa3c49744144376ac74fea60#diff-efeb7ea07fd4b50848dbba91d0e410e1)

**Comment by dcecile** [comment]
- Soft page faults also cost time, about [175 μs per Mb](https://zeuxcg.org/2014/12/21/page-fault-queue/)

**Comment by dcecile** [comment]
Name: stream
