### ISSUE TITLE
Extend memory management for efficiency

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-ideas#5]
Extend #1 for the following...

### Requirements

- Take into account TLB contention
- Take into account soft page faults

### Tasks

- [x] Research soft faults and options to make allocation and use more deterministic
- [x] Find out why my system has low limits on anonymous transparent huge pages
- [x] Test if `madvise(MADV_FREE)` can trigger a transparent huge page split
- [x] Test performance of reserving 1 GiB of virtual memory
- [x] Test if `mprotect(PROT_NONE)` can trigger a transparent huge page split
- [x] Find a good default max stack size
- [x] Solve the transparent huge page alignment issue
- [x] Walk through user-level 4 MiB page management
- [x] Pick a stack guard size
- [x] Design for less-granular allocation/deallocation
- [x] Design background thread involvement
- [ ] Document the results

**Comment by dcecile** [comment]
- Soft page faults also cost time, about [175 μs per Mb](https://zeuxcg.org/2014/12/21/page-fault-queue/)
- In Linux, [MAP_POPULATE](http://man7.org/linux/man-pages/man2/mmap.2.html) might be able to counteract this
- In Windows, maybe [VirtualLock](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-virtuallock) followed by [VirtualUnlock](https://docs.microsoft.com/en-ca/windows/desktop/api/memoryapi/nf-memoryapi-virtualunlock) would work

**Comment by dcecile** [comment]
- What I thought were low THP limits were actually the symptoms of an aging system with low memory
- Lots of `thp_fault_fallback` in `/proc/vmstat`
- After restarting, no more fault fallback, as much memory as I want going into huge pages
- My 4 MiB assumption was actually incorrect -- THP works fine for 2 MiB _as long as the memory is aligned to a 2 MiB address_
- If I was running 4.10, I'd [see](https://github.com/torvalds/linux/commit/49920d28781dcced10cd30cb9a938e7d045a1c94) that 2 MiB is indeed the THP size
- The default for THP is to have it only enabled for memory marked using `madvise`, this matches my system
- With `madvise` skipped, khugepaged (which runs in the background) did not convert the pages to huge pages

**Comment by dcecile** [comment]
- Oops, my 3.18 doesn't have `MADV_FREE` from 4.5
- `MADV_DONTNEED` is able to split a transparent huge page immediately
- But the transparent huge page gets merged by khugepaged later ([kernel bug](https://bugzilla.kernel.org/show_bug.cgi?id=93111))
- With `max_ptes_none` default 511, this will convert even one 4 KiB page into a 2 MiB transparent huge page (allocating 511 new small pages)
- It'll need to be benchmarked to see if THB helps or hinders
- `PROT_NONE` also splits the transparent huge page

**Comment by dcecile** [comment]
- Anecdotally, lots of processes (mainly Chrome) with over 1 GiB of virtual memory and less than 100 MiB of resident memory
- Fine to reserve (`PROT_NONE`) 64 TiB in Linux, 128 TiB fails, takes less than 0.04s (maybe 0.01s slower than reserving 1 MiB), shows up properly in `htop`

**Comment by dcecile** [comment]
- Linux default stack size sounds like 8 MiB, verified via `/proc/self/limits`
